// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpofewohvpggmmhgaqxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdwb2Zld29odnBnZ21taGdhcXhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MTY1OTgsImV4cCI6MjA2Mzk5MjU5OH0.4-NUhAjTLNbkOFegx3_VWBFgpPxrW5uOl9talnmnyM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);